job:
  image: 'hmctspublic.azurecr.io/disposer/idam-user:latest'
  ingressHost: disposer-idam-user-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment}}.internal
  kind: CronJob
  schedule: "0 22 * * *"
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  aadIdentityName: disposer
  keyVaults:
    disposer:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  global:
    jobKind: CronJob
