job:
  image: 'https://hmctspublic.azurecr.io/ccd/ccd-idam-disposer:latest'
  kind: CronJob
  schedule: "0 22 * * *"
  startingDeadlineSeconds: 600
  concurrencyPolicy: Forbid
  ingressHost: idam-user-disposer-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: disposer
  global:
    jobKind: CronJob
