#Application specific properties
idam:
  s2s-auth:
    url: http://localhost:5000

lau:
  api:
    url: ${LAU_API_URL:http://localhost:5000}

dummy-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

wiremock-debug: false

restorer:
  requests.limit: 10
