#Application specific properties
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic

logging:
  level:
    root: warn
    uk.gov.hmcts.reform: debug


idam:
  s2s-auth:
    url: http://localhost:5000

ccd:
  role.assignment:
    host: ${ROLE_ASSIGNMENT_HOST:localhost:5000}


dummy-jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

wiremock-debug: false

role-assignments:
  max-page-size: 4

stale-users:
  # role that citizen user must have among other, otherwise account will be left untouched
  mandatory-role-for-citizen: citizen
  citizen-roles: claimant,defendant,divorce-private-beta,cmc-private-beta,probate-private-beta
  citizen-letter-role-pattern: letter-

