job:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}.preview.platform.hmcts.net
  kind: CronJob
  schedule: "*/20 * * * *"
  startingDeadlineSeconds: 180
  concurrencyPolicy: Forbid

global:
  jobKind: CronJob
